server:
  port: 9888
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9777/eureka/

spring:
  redis:
    host: localhost
    port: 6379
    password:

    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms