eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:9777/eureka/

spring:
  data:
    cassandra:
      contact_points: cassandra
  redis:
    host: redis
    port: 6379
    password: